In [1]:
import numpy as np
ar=np.array([4,5,7,1,3,9,3,11])
ar

array([ 4,  5,  7,  1,  3,  9,  3, 11])

In [35]:
ind=[4,6,0,3]
ar[ind]

array([12, 55, 66,  1])

In [36]:
ar.put(ind,1)
ar

array([ 1,  5,  7,  1,  1,  9,  1, 11])

In [37]:
ar.put(ind,[12,55,66,22])
ar

array([66,  5,  7, 22, 12,  9, 55, 11])

In [2]:
t=np.random.randn(3,4)
ix=np.array([2,1,0])
inx=np.array([2,0,3,1,0])
t

array([[-1.62677492, -0.31714615,  0.01538159, -0.08281173],
       [ 0.76706028, -0.77318164,  0.66155797,  0.53695046],
       [-0.15840773,  0.64362261, -0.19087177,  0.0395312 ]])

In [3]:
t.take(ix,axis=1)

array([[ 0.01538159, -0.31714615, -1.62677492],
       [ 0.66155797, -0.77318164,  0.76706028],
       [-0.19087177,  0.64362261, -0.15840773]])

In [56]:
t.take(inx,axis=1)

array([[-2.58907558, -0.61395387, -0.09660758,  0.61900968, -0.61395387],
       [-0.30738233, -0.80023479,  0.51063773,  0.02403341, -0.80023479],
       [-0.0673576 , -0.03269882, -0.10254393,  0.72522564, -0.03269882]])