In [21]:
import numpy as np

In [22]:
a=np.random.randn(5,5)

In [23]:
a

array([[ 0.31001851,  0.5664    ,  0.52222198, -0.65607606, -0.5090569 ],
       [-0.09933308, -0.07098628, -0.49790063,  0.69502945, -0.31314857],
       [-0.11566038,  0.54940297, -1.50698533,  0.19562149,  0.82434982],
       [ 0.84827262,  2.24686159, -1.52782215,  0.18055576, -0.40390227],
       [ 0.85716038,  1.06466966,  0.91648281, -1.68676587, -0.87803134]])

In [25]:
x=np.array(a,dtype='int')

In [26]:
x

array([[ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0, -1,  0,  0],
       [ 0,  2, -1,  0,  0],
       [ 0,  1,  0, -1,  0]])

In [27]:
y=a.astype(int)

In [28]:
y

array([[ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0, -1,  0,  0],
       [ 0,  2, -1,  0,  0],
       [ 0,  1,  0, -1,  0]])

In [30]:
b=abs(x)
print(b)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 2 1 0 0]
 [0 1 0 1 0]]


In [15]:
b[0][2]

2

In [33]:
b[]
print(b)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 2 1 0 0]
 [0 1 0 1 0]]


In [43]:
seq=[1,2,4,6,8,29,5,3,0,6,2,5,7,1,5,3,2,7,8,99]

In [46]:
seq[::3]

[1, 6, 5, 6, 7, 3, 8]

In [47]:
seq.count(2)

3

In [54]:
seq.sort()

In [55]:
seq

[0, 1, 1, 2, 2, 2, 3, 3, 4, 5, 5, 5, 6, 6, 7, 7, 8, 8, 29, 99]

In [60]:
seq[::-1]

[99, 29, 8, 8, 7, 7, 6, 6, 5, 5, 5, 4, 3, 3, 2, 2, 2, 1, 1, 0]

In [64]:
print(l)

None


In [65]:
li=[1,3,2,4,2]

In [66]:
li.sort(reverse=True)

In [67]:
li

[4, 3, 2, 2, 1]

In [68]:
seq1 = ['foo', 'bar', 'baz']
seq2 = ['one', 'two', 'three']
zipped = zip(seq1, seq2)

In [70]:
list(zipped)

[('foo', 'one'), ('bar', 'two'), ('baz', 'three')]

In [74]:
a=1
b=2
c=4
print(f'these are the values of a={a},b={b},c={c}')

these are the values of a=1,b=2,c=4


In [75]:
a = {1, 2, 3, 4, 5}
b = {3, 4, 5, 6, 7, 8}

In [77]:
a.update(b)

In [78]:
a

{1, 2, 3, 4, 5, 6, 7, 8}

In [79]:
b

{3, 4, 5, 6, 7, 8}

In [80]:
a = {1, 2, 3, 4, 5}
b = {3, 4, 5, 6, 7, 8}

In [81]:
a|b

{1, 2, 3, 4, 5, 6, 7, 8}

# Strinping

In [18]:
import re
def clean_strings(strings):
    result = []
    for value in strings:
        value = value.strip()
        value = re.sub('[!#?@-]', '', value)
        value = value.title()
        result.append(value)
    return result

states = [' Alabama ', 'Georgia!', 'Georgia--', 'georgia@@', 'FlOrIda','south carolina##', 'West virginia?']
clean_strings(states)

['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'South Carolina',
 'West Virginia']

In [100]:
import re
def clean_strings(strings):
    result = []
    for value in strings:
        value = value.strip()
        value = re.sub('[!#?@-]', '', value)
        value = value.title()
        result.append(value)
    return result

states = [' Alabama ', 'Georgia!', 'Georgia--', 'georgia@@', 'FlOrIda','south carolina##', 'West virginia?']
clean_strings(states)

['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'South Carolina',
 'West Virginia']

In [100]:
#s="Asif      Ahmed    Jamil     Ahmed"

s='my#@name   is!@#    Asif aHMED'
st=re.sub('[!@#$%^&,*()_+]',' ',s)
#st=st.strip()
st=" ".join(st.split())


In [101]:
print(st)

my name is Asif aHMED


In [79]:
name=input()
#name="Asif ##     Ahmed##    Jamil     Ahmed"
name=re.sub('[#]','',name)
name=name.strip()
name=" ".join(name.split())
print(name)

aa##  dfddd
aa dfddd


In [127]:
def remove_punctuation(value):
    s=re.sub('[!?#@-]', '', value)
    return s.strip()


states = [' Alabama ', 'Georgia!', 'Georgia--', 'georgia@@', 'FlOrIda','south carolina##', 'West virginia?']
for x in map(remove_punctuation, states):
    print(x)

Alabama
Georgia
Georgia
georgia
FlOrIda
south carolina
West virginia


In [112]:
list1=('egg',1000),('milk',1034),('butter',500),('peach',200)
list1=sorted(list1,key = lambda x:x[1])
print(list1)

[('peach', 200), ('butter', 500), ('egg', 1000), ('milk', 1034)]


In [113]:
type(list1)

list

In [122]:
import pprint as pp
l1=[{'make':'car','model':'lush','year':2000},{'make':'bike','model':'stylish','year':1990},{'make':'truck','model':'metal','year':1995}]
l1=sorted(l1,key=lambda x:x['year'])
#l2=l1.sort(key=lambda x:x['year'])
#print(l2)
pp.pprint(l1)

[{'make': 'bike', 'model': 'stylish', 'year': 1990},
 {'make': 'truck', 'model': 'metal', 'year': 1995},
 {'make': 'car', 'model': 'lush', 'year': 2000}]


In [118]:
type(l1)

list

In [104]:
l=[1,2,3,4,56,6]
k=list(filter(lambda x:x%2==0,l))

In [105]:
k

[2, 4, 56, 6]

In [108]:
l=[1,2,3,4,56,6]
k=list(map(lambda x:x*2,l))

In [109]:
k

[2, 4, 6, 8, 112, 12]

In [14]:
wbf4=lambda s,w:s.split()[s.split().index(w)-1] if w in s else None
sentence='my name is anything else'
n=input("enter awword")
print(wbf4(sentence,n))

enter awwordis
name
